-- Applied to Supabase project lekxbuzxnhyznblhutxz as migration "portal_account_nickname" (2026-10-07).
-- Adds an optional per-link nickname, returns it from portal_ai_apps, and adds portal_rename.
alter table public.portal_hub_links add column if not exists nickname text;
alter table public.portal_hub_links drop constraint if exists portal_hub_links_nickname_len;
alter table public.portal_hub_links add constraint portal_hub_links_nickname_len check (nickname is null or char_length(nickname) between 1 and 40);

create or replace function public.portal_ai_apps(p_token text) returns jsonb language plpgsql stable security definer set search_path to 'public','extensions' as $function$ declare a uuid; accts jsonb; n int; begin select s.account_id into a from public.portal_sessions s where s.token_hash = encode(digest(coalesce(p_token,''),'sha256'),'hex') and s.expires_at > now(); if a is null then return jsonb_build_object('ok',false); end if; select count(*) into n from public.portal_hub_links where account_id = a; select coalesce(jsonb_agg(jsonb_build_object('id', l.hub_user_id, 'label', coalesce(u.email,'AI account'), 'nickname', l.nickname, 'linked_at', l.created_at, 'clients', coalesce((select jsonb_agg(jsonb_build_object('name', coalesce(c.client_name,'AI app'), 'last_active', t.last_at) order by t.last_at desc) from (select client_id, max(created_at) last_at from public.oauth_tokens where user_id = l.hub_user_id and revoked = false and expires_at > now() group by client_id) t join public.oauth_clients c on c.client_id = t.client_id), '[]'::jsonb)) order by l.created_at), '[]'::jsonb) into accts from public.portal_hub_links l left join public.users u on u.id = l.hub_user_id where l.account_id = a; return jsonb_build_object('ok',true,'linked',n>0,'needs_unlock',n>=1,'accounts',accts); end $function$;

create or replace function public.portal_rename(p_token text, p_hub_user uuid, p_nickname text) returns jsonb language plpgsql security definer set search_path to 'public','extensions' as $function$ declare a uuid; nick text; cnt int; begin select s.account_id into a from public.portal_sessions s where s.token_hash = encode(digest(coalesce(p_token,''),'sha256'),'hex') and s.expires_at > now(); if a is null then return jsonb_build_object('ok',false,'error','Not signed in.'); end if; nick := nullif(btrim(regexp_replace(coalesce(p_nickname,''), '[[:cntrl:]]', '', 'g')), ''); if nick is not null and char_length(nick) > 40 then return jsonb_build_object('ok',false,'error','Name must be 40 characters or fewer.'); end if; update public.portal_hub_links set nickname = nick where account_id = a and hub_user_id = p_hub_user; get diagnostics cnt = row_count; if cnt = 0 then return jsonb_build_object('ok',false,'error','Account not found.'); end if; return jsonb_build_object('ok',true,'nickname',nick); end $function$;
