import {cookies} from "next/headers";
import {SESSION_COOKIE,sessionUser} from "../lib/portal";
import {connectionStatus,type Provider} from "../lib/connections";
import SignOutButton from "./components/SignOutButton";
import ConnectionButton from "./components/ConnectionButton";
import ActivityFeed from "./components/ActivityFeed";
export const dynamic="force-dynamic";
type Notice={kind:"error"|"ok";text:string}|null;
const apps:Array<{id:Provider;name:string;tag:string;icon:string;description:string;pill?:string}>=[
{id:"supabase",name:"Supabase",tag:"Database",icon:"Sb",description:"Projects, databases and edge functions."},
{id:"vercel",name:"Vercel",tag:"Deployments",icon:"▲",description:"Projects, deployments and hosting."},
{id:"canva",name:"Canva",tag:"Design",icon:"Ca",description:"Designs and your creative workspace."},
{id:"github",name:"GitHub",tag:"Development",icon:"GH",description:"Repositories, branches and commits. GitHub needs an OAuth app set up first.",pill:"Needs OAuth app"}
];
function Landing(){return <div className="page"><header className="top"><a className="brand" href="/"><span className="logo">H</span><span>Handoff Hub</span></a><a className="navButton" href="/login">Sign in</a></header><main className="wrap"><section className="landingHero"><div className="landingCopy"><span className="eyebrow">Handoff Hub</span><h1>One place to <span>connect your tools.</span></h1><p>Connect services the way modern AI platforms do: authorize on the provider, return to Handoff Hub, and keep the connection encrypted for future tool calls.</p><div className="actions"><a className="primaryLink" href="/login">Get started</a><a className="secondaryLink" href="/connect/setup">How connections work</a></div></div><div className="landingPanel"><div className="panelHeader"><span>OAuth connection</span><span className="statusDot">Ready</span></div><div className="miniCard"><strong>1 · Connect</strong><span>Choose a provider</span></div><div className="miniCard"><strong>2 · Authorize</strong><span>Approve on the provider</span></div><div className="miniCard"><strong>3 · Use</strong><span>Connection stays encrypted</span></div><p>Handoff Hub never asks for provider passwords or raw API keys.</p></div></section></main><footer className="foot"><span>Handoff Hub</span><span>Secure context handoff for AI workflows</span></footer></div>}
async function Dashboard({email,sessionToken,notice}:{email:string;sessionToken:string;notice:Notice}){const connections=await connectionStatus(sessionToken).catch(()=>[]);const connected=new Map(connections.map(c=>[c.provider,c]));return <div className="page"><header className="top"><a className="brand" href="/"><span className="logo">H</span><span>Handoff Hub</span></a><div className="userChip"><span className="avatar">{email[0].toUpperCase()}</span><span className="userEmail">{email}</span><SignOutButton/></div></header><main className="wrap"><section className="dash"><span className="eyebrow">Signed in</span><h1>Connect your apps</h1><p className="lead">Click Connect to open the provider's official authorization page. Approve access there, then return automatically.</p>{notice&&<div className={"notice wide "+notice.kind} role="alert">{notice.text}</div>}<div className="grid">{apps.map(a=>{const c=connected.get(a.id);return <article className={"card"+(c?"":" dim")} key={a.id}><div className="cardTop"><div className="appIcon">{a.icon}</div><span className={"pill "+(c?"connectedPill":"soon")}>{c?"Connected":(a.pill||"Ready to connect")}</span></div><div className="tag">{a.tag}</div><h3>{a.name}</h3><p>{c?.provider_account_name?"Connected as "+c.provider_account_name+".":a.description}</p><ConnectionButton provider={a.id} connected={!!c}/></article>})}</div></section><ActivityFeed token={sessionToken} connections={connections}/></main><footer className="foot"><span className="shield">✓</span>OAuth tokens stay server-side and encrypted. Provider passwords never reach Handoff Hub.</footer></div>}
export default async function Home({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const jar=await cookies();const token=jar.get(SESSION_COOKIE)?.value;const user=await sessionUser(token);const sp=await searchParams;const err=typeof sp.connection_error==="string"?sp.connection_error:"";const ok=typeof sp.connected==="string"?sp.connected:"";const notice:Notice=err?{kind:"error",text:err}:ok?{kind:"ok",text:"Connected "+ok+"."}:null;return user&&token?<Dashboard email={user.email} sessionToken={token} notice={notice}/>:<Landing/>}
