import {cookies} from "next/headers";
import {SESSION_COOKIE,sessionUser} from "../lib/portal";
import {connectionStatus,type Provider} from "../lib/connections";
import SignOutButton from "./components/SignOutButton";
import ConnectionButton from "./components/ConnectionButton";
import ActivityFeed from "./components/ActivityFeed";
import AiApps from "./components/AiApps";
import ConnectorDirectory from "./components/ConnectorDirectory";
export const dynamic="force-dynamic";
type Notice={kind:"error"|"ok";text:string}|null;
const apps:Array<{id:Provider;name:string;tag:string;icon:string;description:string}>=[
{id:"github",name:"GitHub",tag:"Development",icon:"GH",description:"Repositories, branches, issues and development workflows."},
{id:"canva",name:"Canva",tag:"Design",icon:"Ca",description:"Designs and your creative workspace."},
{id:"vercel",name:"Vercel",tag:"Infrastructure",icon:"▲",description:"Projects and deployments from your Vercel account."},
{id:"supabase",name:"Supabase",tag:"Data",icon:"Sb",description:"Projects, databases and edge functions."}
];
function Landing(){return <div className="site"><header className="top"><a className="brand" href="/"><span className="logo">H</span><span>Handoff Hub</span></a><nav><a href="/connect/setup">How it works</a><a className="navButton" href="/login">Sign in</a></nav></header><main className="wrap"><section className="landingHero"><div><span className="eyebrow">Secure integrations</span><h1>Your apps.<br/><span>One secure handoff.</span></h1><p>Connect the tools you already use to power AI workflows. Authorize directly with each provider and keep credentials isolated to your account.</p><div className="actions"><a className="primaryLink" href="/login">Get started</a><a className="secondaryLink" href="/connect/setup">Learn how it works →</a></div><div className="trustRow"><span>✓ OAuth authorization</span><span>✓ Account-isolated</span><span>✓ Server-side tokens</span></div></div><div className="heroVisual"><div className="visualTop"><span>HANDOFF HUB</span><span className="live"><i/>LIVE</span></div><div className="flow"><div className="flowNode"><b>01</b><strong>Your account</strong><span>Choose an app</span></div><div className="flowLine"/><div className="flowNode active"><b>02</b><strong>Provider</strong><span>Approve access</span></div><div className="flowLine"/><div className="flowNode"><b>03</b><strong>Handoff</strong><span>Use securely</span></div></div><div className="visualFooter">No provider passwords are sent to Handoff Hub.</div></div></section><section className="stats"><div><b>OAuth-first</b><span>Provider-hosted authorization</span></div><div><b>Private by default</b><span>Each account has its own connections</span></div><div><b>Built for AI</b><span>Ready for tool-enabled workflows</span></div></section></main><footer className="foot">Handoff Hub · Secure context handoff for AI workflows</footer></div>}
async function Dashboard({email,sessionToken,notice}:{email:string;sessionToken:string;notice:Notice}){const connections=await connectionStatus(sessionToken).catch(()=>[]);const connected=new Map(connections.map(c=>[c.provider,c]));return <div className="site"><header className="top"><a className="brand" href="/"><span className="logo">H</span><span>Handoff Hub</span></a><div className="userChip"><span className="avatar">{email[0].toUpperCase()}</span><span className="userEmail">{email}</span><SignOutButton/></div></header><main className="wrap dashboard"><div className="dashHead"><div><span className="eyebrow">Workspace</span><h1>Connections</h1><p>Manage the apps connected to your Handoff Hub account.</p></div><div className="secureBadge"><i/> Secure session</div></div>{notice&&<div className={"notice wide "+notice.kind}>{notice.text}</div>}<section className="quickGrid">{apps.map(a=>{const c=connected.get(a.id);return <article className="quickCard" key={a.id}><div className={"brandIcon brand-"+a.id}>{a.icon}</div><div className="quickCopy"><div><span className="category">{a.tag}</span><h3>{a.name}</h3></div><span className={"state "+(c?"on":"")}>{c?"Connected":"Not connected"}</span></div><p>{c?.provider_account_name?"Connected as "+c.provider_account_name+".":a.description}</p><ConnectionButton provider={a.id} connected={!!c}/></article>})}</section><ConnectorDirectory connected={new Set(connections.map(c=>c.provider))}/><AiApps token={sessionToken}/><ActivityFeed token={sessionToken} connections={connections}/></main><footer className="foot"><span className="shield">✓</span> Credentials stay server-side and encrypted.</footer></div>}
export default async function Home({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const jar=await cookies();const token=jar.get(SESSION_COOKIE)?.value;const user=await sessionUser(token);const sp=await searchParams;const err=typeof sp.connection_error==="string"?sp.connection_error:"";const ok=typeof sp.connected==="string"?sp.connected:"";const notice:Notice=err?{kind:"error",text:err}:ok?{kind:"ok",text:"Connected "+ok+"."}:null;return user&&token?<Dashboard email={user.email} sessionToken={token} notice={notice}/>:<Landing/>}
