import crypto from 'node:crypto';

const SUPABASE_URL=process.env.SUPABASE_URL;
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const ENC_KEY=process.env.PROVIDER_TOKEN_ENC_KEY;
const base=()=> (process.env.PUBLIC_BASE_URL || (process.env.VERCEL_PROJECT_PRODUCTION_URL ? 'https://'+process.env.VERCEL_PROJECT_PRODUCTION_URL : 'http://localhost:3000')).replace(/\/$/,'');
const CFG={
 github:{client:'GITHUB_CLIENT_ID',secret:'GITHUB_CLIENT_SECRET',auth:'https://github.com/login/oauth/authorize',token:'https://github.com/login/oauth/access_token',scope:'read:user user:email repo'},
 canva:{client:'CANVA_CLIENT_ID',secret:'CANVA_CLIENT_SECRET',auth:'https://www.canva.com/api/oauth/authorize',token:'https://api.canva.com/rest/v1/oauth/token',scope:'design:meta:read design:content:read profile:read'},
 vercel:{client:'VERCEL_CLIENT_ID',secret:'VERCEL_CLIENT_SECRET',auth:'https://vercel.com/oauth/authorize',token:'https://api.vercel.com/login/oauth/token',scope:'openid email profile offline_access'}
};
const hash=v=>crypto.createHash('sha256').update(v).digest('hex'), rnd=(n=32)=>crypto.randomBytes(n).toString('base64url');
const pkce=v=>crypto.createHash('sha256').update(v).digest('base64url');
function env(v,n){if(!v)throw new Error(n+' is not configured on the Handoff Hub server');return v}
async function rest(path,o={}){env(SUPABASE_URL,'SUPABASE_URL');env(SERVICE_KEY,'SUPABASE_SERVICE_ROLE_KEY');const h={apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json'};if(o.prefer)h.Prefer=o.prefer;const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method:o.method||'GET',headers:h,body:o.body===undefined?undefined:JSON.stringify(o.body)});const t=await r.text();let d={};try{d=t?JSON.parse(t):{};}catch{}if(!r.ok)throw new Error('Supabase request failed: '+r.status);return d}
function encrypt(v){env(ENC_KEY,'PROVIDER_TOKEN_ENC_KEY');const k=crypto.createHash('sha256').update(ENC_KEY).digest(),iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',k,iv),d=Buffer.concat([c.update(v,'utf8'),c.final()]);return [iv,c.getAuthTag(),d].map(x=>x.toString('base64url')).join('.')}
async function account(session){if(!session)return null;const rows=await rest('portal_sessions?token_hash=eq.'+encodeURIComponent(hash(session))+'&expires_at=gt.'+encodeURIComponent(new Date().toISOString())+'&select=account_id&limit=1');return rows?.[0]?.account_id||null}
function callback(p){return base()+'/api/provider-oauth?callback=1&provider='+encodeURIComponent(p)}
async function start(p,session){const id=await account(session),c=CFG[p];if(!id)throw new Error('Not signed in.');if(!c)throw new Error('Unsupported provider');env(process.env[c.client],c.client);env(process.env[c.secret],c.secret);env(ENC_KEY,'PROVIDER_TOKEN_ENC_KEY');const state=rnd(),ver=rnd(48);await rest('provider_oauth_flows',{method:'POST',prefer:'return=minimal',body:{state_hash:hash(state),account_id:id,provider:p,code_verifier:ver,expires_at:new Date(Date.now()+600000).toISOString()}});const u=new URL(c.auth);u.searchParams.set('client_id',process.env[c.client]);u.searchParams.set('redirect_uri',callback(p));u.searchParams.set('response_type','code');u.searchParams.set('state',state);u.searchParams.set('code_challenge',pkce(ver));u.searchParams.set('code_challenge_method','S256');u.searchParams.set('scope',c.scope);return u.toString()}
async function exchange(p,code,row){const c=CFG[p],form=new URLSearchParams({grant_type:'authorization_code',client_id:process.env[c.client],client_secret:process.env[c.secret],code,redirect_uri:callback(p),code_verifier:row.code_verifier}),h={'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'};if(p==='canva')h.Authorization='Basic '+Buffer.from(process.env[c.client]+':'+process.env[c.secret]).toString('base64');const r=await fetch(c.token,{method:'POST',headers:h,body:form}),d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.message||d.error||'OAuth token exchange failed');return d}
async function profile(p,t){const h={Authorization:'Bearer '+t,Accept:'application/json'};if(p==='github'){const r=await fetch('https://api.github.com/user',{headers:{...h,'X-GitHub-Api-Version':'2022-11-28'}}),d=await r.json().catch(()=>({}));return r.ok?{id:String(d.id),name:d.login||d.name}:{}}
if(p==='canva'){const r=await fetch('https://api.canva.com/rest/v1/users/me/profile',{headers:h}),d=await r.json().catch(()=>({}));return r.ok?{name:d?.profile?.display_name}:{}}
const r=await fetch('https://api.vercel.com/login/oauth/userinfo',{headers:h}),d=await r.json().catch(()=>({}));return r.ok?{id:d.sub,name:d.preferred_username||d.name||d.email}:{}}
async function complete(p,code,state){const rows=await rest('provider_oauth_flows?state_hash=eq.'+encodeURIComponent(hash(state))+'&expires_at=gt.'+encodeURIComponent(new Date().toISOString())+'&select=account_id,provider,code_verifier&limit=1'),row=rows?.[0];if(!row||row.provider!==p)throw new Error('Invalid or expired OAuth state');const t=await exchange(p,code,row),pr=await profile(p,t);await rest('provider_connections?account_id=eq.'+encodeURIComponent(row.account_id)+'&provider=eq.'+encodeURIComponent(p),{method:'DELETE',prefer:'return=minimal'}).catch(()=>{});await rest('provider_connections',{method:'POST',prefer:'return=minimal',body:{account_id:row.account_id,provider:p,access_token:encrypt(t.access_token),refresh_token:t.refresh_token?encrypt(t.refresh_token):null,expires_at:t.expires_in?new Date(Date.now()+Number(t.expires_in)*1000).toISOString():null,provider_account_id:pr.id||null,provider_account_name:pr.name||null,scope:t.scope||null}});const ticket=rnd();await rest('provider_oauth_flows?state_hash=eq.'+encodeURIComponent(hash(state)),{method:'PATCH',prefer:'return=minimal',body:{completed_at:new Date().toISOString(),ticket_hash:hash(ticket),code_verifier:null}});return ticket}
async function consume(p,session,ticket){const id=await account(session);if(!id)throw new Error('Not signed in.');const rows=await rest('provider_oauth_flows?ticket_hash=eq.'+encodeURIComponent(hash(ticket))+'&provider=eq.'+encodeURIComponent(p)+'&account_id=eq.'+encodeURIComponent(id)+'&completed_at=not.is.null&consumed_at=is.null&select=state_hash&limit=1');if(!rows?.[0])throw new Error('Invalid or expired connection ticket');await rest('provider_oauth_flows?ticket_hash=eq.'+encodeURIComponent(hash(ticket)),{method:'PATCH',prefer:'return=minimal',body:{consumed_at:new Date().toISOString()}});return true}
async function status(session){const id=await account(session);if(!id)throw new Error('Not signed in.');return await rest('provider_connections?account_id=eq.'+encodeURIComponent(id)+'&select=provider,provider_account_name,scope,updated_at')}
async function disconnect(p,session){const id=await account(session);if(!id)throw new Error('Not signed in.');if(!CFG[p])throw new Error('Unsupported provider');await rest('provider_connections?account_id=eq.'+encodeURIComponent(id)+'&provider=eq.'+encodeURIComponent(p),{method:'DELETE',prefer:'return=minimal'});return {ok:true}}
export async function providerAction(b){if(b.action==='start')return {authorization_url:await start(b.provider,b.portal_session)};if(b.action==='consume')return {ok:await consume(b.provider,b.portal_session,b.ticket)};if(b.action==='status')return {connections:await status(b.portal_session),providers:Object.entries(CFG).map(([provider,c])=>({provider,configured:Boolean(process.env[c.client]&&process.env[c.secret])}))};if(b.action==='disconnect')return disconnect(b.provider,b.portal_session);throw new Error('Unknown action')}
export async function providerCallback(p,code,state){return complete(p,code,state)}
