import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { project, getState, mutate } from './store.js';
import { z } from 'zod';
import { hfModels, hfChat, githubGetFile, githubCommitFile, vercelGetLatestDeployment, vercelTriggerRedeploy } from './integrations.js';
import { optimizeTask } from './optimizer.js';
import { runHealthCheck } from './worker.js';

const projectId = z.string().min(1).optional().describe('Optional project identifier within your private account. If omitted, uses your own default project; it is never shared with another user.');

export function createServer(userId) {
  const server = new McpServer({ name: 'handoff-hub', version: '0.11.0' });
  const text = value => ({ content: [{ type: 'text', text: JSON.stringify(value, null, 2) }] });

  server.tool('remember', 'Save durable context to your private Handoff Hub memory. Call this proactively when you learn a fact, decision, or context another session or AI agent will need later.', { project_id: projectId, memory: z.string().min(1), source: z.string().optional(), tags: z.array(z.string()).optional() }, async input => text(await mutate(userId, state => { const p = project(state, input.project_id ?? 'default'); const item = { id: crypto.randomUUID(), project_id: input.project_id ?? 'default', memory: input.memory, source: input.source ?? 'unknown', tags: input.tags ?? [], at: new Date().toISOString() }; p.memories.unshift(item); p.memories = p.memories.slice(0, 500); return item; })));
  server.tool('recall', 'Retrieve private Handoff Hub memory. Call this at the start of a task before asking for context that may already be saved by another session or AI.', { project_id: projectId, query: z.string().optional(), limit: z.number().int().min(1).max(50).optional() }, async ({ project_id, query = '', limit = 10 }) => { const state = await getState(userId); const p = project(state, project_id ?? 'default'); const words = query.toLowerCase().split(/\s+/).filter(Boolean); const ranked = p.memories.map(m => ({ m, score: words.reduce((n, w) => n + (m.memory.toLowerCase().includes(w) ? 1 : 0), 0) })).sort((a, b) => b.score - a.score).slice(0, limit).map(x => x.m); return text(ranked); });
  server.tool('record_event', 'Log a meaningful completed action so another AI agent can continue without manual re-explanation. Call this proactively after meaningful work.', { project_id: projectId, agent: z.string().min(1), action: z.string().min(1), details: z.string().optional() }, async input => text(await mutate(userId, state => { const p = project(state, input.project_id ?? 'default'); const event = { id: crypto.randomUUID(), project_id: input.project_id ?? 'default', agent: input.agent, action: input.action, details: input.details, at: new Date().toISOString() }; p.events.unshift(event); p.events = p.events.slice(0, 100); return event; })));
  server.tool('recent_events', 'Read recent private cross-agent activity. Call this at the start of a session to catch up on what another AI already did.', { project_id: projectId, limit: z.number().int().min(1).max(100).optional() }, async ({ project_id, limit = 20 }) => text(project(await getState(userId), project_id ?? 'default').events.slice(0, limit)));
  server.tool('get_project_state', 'Read your private project state including summary, decisions, blockers, events, memories, and integrations.', { project_id: projectId }, async ({ project_id }) => text(project(await getState(userId), project_id ?? 'default')));
  server.tool('update_project_state', 'Update private project status so your other AI agents can continue from the same state. Call this proactively after meaningful work.', { project_id: projectId, summary: z.string().min(1), decisions: z.array(z.string()).optional(), blockers: z.array(z.string()).optional(), agent: z.string().min(1).optional() }, async input => text(await mutate(userId, state => { const p = project(state, input.project_id ?? 'default'); p.summary = input.summary; p.decisions = input.decisions ?? p.decisions ?? []; p.blockers = input.blockers ?? p.blockers ?? []; p.updated_at = new Date().toISOString(); p.last_agent = input.agent ?? p.last_agent ?? 'unknown'; p.events.unshift({ type: 'state_update', agent: p.last_agent, summary: input.summary, at: p.updated_at }); p.events = p.events.slice(0, 100); return p; })));
  server.tool('set_integration', 'Register an integration available to a private Handoff Hub project. This records capabilities only; it does not grant credentials.', { project_id: projectId, name: z.string().min(1), type: z.string().min(1), capabilities: z.array(z.string()).optional() }, async input => text(await mutate(userId, state => { const p = project(state, input.project_id ?? 'default'); p.integrations[input.name] = { type: input.type, capabilities: input.capabilities ?? [], updated_at: new Date().toISOString() }; return p.integrations[input.name]; })));
  server.tool('list_projects', 'List only your own Handoff Hub projects. Never includes another user\'s projects.', {}, async () => text(Object.values((await getState(userId)).projects)));

  // Task handoff between AI agents (restored: these were referenced in project
  // history but had dropped out of the registered tool list).
  server.tool('hand_off_task', 'Hand a concrete piece of work to another AI agent (e.g. chatgpt or claude) so it can pick it up without the user re-explaining context. The other agent sees it via get_my_handoffs and closes it with complete_handoff.', { project_id: projectId, agent: z.string().min(1).describe('Your own agent name, e.g. "claude" or "chatgpt".'), to_agent: z.string().min(1).describe('Agent the task is for, e.g. "chatgpt" or "claude".'), task: z.string().min(1), context: z.string().optional() }, async input => text(await mutate(userId, state => { const pid = input.project_id ?? 'default'; const p = project(state, pid); const item = { id: crypto.randomUUID(), project_id: pid, task: input.task, context: input.context, from_agent: input.agent.toLowerCase(), to_agent: input.to_agent.toLowerCase(), status: 'pending', created_at: new Date().toISOString() }; p.tasks = p.tasks || []; p.tasks.unshift(item); p.tasks = p.tasks.slice(0, 200); p.events.unshift({ type: 'handoff_created', agent: item.from_agent, to_agent: item.to_agent, task: item.task, at: item.created_at }); p.events = p.events.slice(0, 100); return item; })));
  server.tool('get_my_handoffs', 'List tasks another AI agent handed to you. Call this at the start of a session, before asking the user for context. Returns pending tasks by default.', { project_id: projectId, agent: z.string().min(1).describe('Your own agent name, e.g. "claude" or "chatgpt".'), include_done: z.boolean().optional() }, async ({ project_id, agent, include_done = false }) => { const p = project(await getState(userId), project_id ?? 'default'); const me = agent.toLowerCase(); return text((p.tasks || []).filter(t => t.to_agent === me && (include_done || t.status !== 'done'))); });
  server.tool('complete_handoff', 'Mark a handed-off task as done with a short result so the agent that created it, and anyone reading project state, can see the outcome.', { project_id: projectId, agent: z.string().min(1).describe('Your own agent name.'), task_id: z.string().min(1), result: z.string().min(1) }, async input => text(await mutate(userId, state => { const p = project(state, input.project_id ?? 'default'); const t = (p.tasks || []).find(x => x.id === input.task_id); if (!t) return { error: `No handoff task found with id ${input.task_id}` }; t.status = 'done'; t.result = input.result; t.completed_by = input.agent.toLowerCase(); t.completed_at = new Date().toISOString(); p.events.unshift({ type: 'handoff_completed', agent: t.completed_by, task: t.task, at: t.completed_at }); p.events = p.events.slice(0, 100); return t; })));

  server.tool('huggingface_models', 'List Hugging Face chat models currently exposing a free provider. This is a free-only discovery tool; it never enables paid inference.', { search: z.string().optional() }, async ({ search = '' }) => text(await hfModels(search)));
  server.tool('huggingface_chat', 'Run an auxiliary AI request through Hugging Face Inference Providers. The Hub only permits a provider explicitly reported as free and never enables pay-as-you-go fallback.', { model: z.string().min(1), prompt: z.string().min(1), system: z.string().optional(), max_tokens: z.number().int().min(1).max(4096).optional() }, async input => text(await hfChat(input)));
  server.tool('optimize_task', 'Run Handoff Hub\'s internal task optimizer. This is not a chat tool: it selects a currently free Hugging Face coding model/provider, produces an integration execution plan, and never claims execution.', { task: z.string().min(1), context: z.string().optional(), max_tokens: z.number().int().min(1).max(4096).optional() }, async input => text(await optimizeTask(input)));

  server.tool('github_get_file', 'Read a file from an allowlisted GitHub repository through Handoff Hub. GitHub credentials stay server-side.', { repository: z.string().min(1), path: z.string().min(1), branch: z.string().optional() }, async input => text(await githubGetFile(input)));
  server.tool('github_commit_file', 'Create or replace a file in an allowlisted GitHub repository through Handoff Hub. GitHub credentials stay server-side; the caller never receives them.', { repository: z.string().min(1), path: z.string().min(1), content: z.string(), message: z.string().min(1), branch: z.string().optional(), sha: z.string().optional() }, async input => text(await githubCommitFile(input)));

  server.tool('vercel_get_deployment', 'Read the latest deployment status for an allowlisted Vercel project through Handoff Hub. Vercel credentials stay server-side.', { projectId: z.string().min(1), target: z.string().optional() }, async input => text(await vercelGetLatestDeployment(input)));
  server.tool('vercel_trigger_redeploy', 'Trigger a redeploy on an allowlisted Vercel project through Handoff Hub (inherits the source deployment\'s settings unless overridden). Vercel credentials stay server-side; the caller never receives them.', { projectId: z.string().min(1), deploymentId: z.string().optional(), name: z.string().optional(), target: z.string().optional() }, async input => text(await vercelTriggerRedeploy(input)));

  server.tool('run_health_check', 'Run the autonomous read-only health check now: Vercel production deployment status, the MCP endpoint\'s own health, and Hugging Face free-model availability. Never writes to GitHub or Vercel, so it never needs approval. The same checks also run automatically once a day via Vercel Cron; call this for an immediate on-demand read instead of waiting for the next scheduled run.', { project_id: projectId, agent: z.string().optional() }, async ({ project_id, agent }) => text(await runHealthCheck(userId, { project_id: project_id ?? 'default', agent: agent ?? 'on-demand' })));

  return server;
}
