import { mutate, project } from './store.js';
import { hfModels, vercelGetLatestDeployment } from './integrations.js';
import { purgeOAuthData } from './oauth-store.js';

function vercelProjectId(){return(process.env.VERCEL_ALLOWED_PROJECTS||'').split(',').map(x=>x.trim()).filter(Boolean)[0]||null;}
function selfBaseUrl(){const host=process.env.VERCEL_PROJECT_PRODUCTION_URL||process.env.VERCEL_URL;return host?`https://${host}`:null;}

export async function runHealthCheck(userId,{agent='worker',project_id='default'}={}){
  const checks={};
  try{const projectId=vercelProjectId();if(!projectId)checks.vercel={ok:null,note:'VERCEL_ALLOWED_PROJECTS is not configured'};else{const dep=await vercelGetLatestDeployment({projectId,target:'production'});checks.vercel={ok:dep.deployment?.state==='READY',deployment:dep.deployment};}}catch(error){checks.vercel={ok:false,error:error.message};}
  try{const base=selfBaseUrl();if(!base)checks.mcp_endpoint={ok:null,note:'No Vercel URL available in this runtime'};else{const r=await fetch(`${base}/api/mcp?deep=1`,{method:'GET'});const body=await r.json().catch(()=>({}));const blocked=r.status===401||r.status===403;checks.mcp_endpoint=blocked?{ok:null,status_code:r.status,note:'Endpoint blocked by deployment protection; inconclusive'}:{ok:r.ok&&body.status==='ok',status_code:r.status,version:body.version,status:body.status,tools:body.tools,...(r.ok?{}:{error:body.error||`HTTP ${r.status}`})};}}catch(error){checks.mcp_endpoint={ok:false,error:error.message};}
  try{const base=selfBaseUrl();if(!base)checks.routes={ok:null,note:'No Vercel URL available in this runtime'};else{const probes=[['/api/canva/oauth/callback',[400]],['/.well-known/oauth-protected-resource/api/mcp',[200]]];const results=[];for(const[path,expected]of probes){const r=await fetch(`${base}${path}`,{method:'GET',redirect:'manual'});results.push({path,status_code:r.status,ok:r.status===401||r.status===403?null:expected.includes(r.status)});}const bad=results.filter(x=>x.ok===false);checks.routes=bad.length?{ok:false,results,error:`unexpected status on ${bad.map(x=>`${x.path} (${x.status_code})`).join(', ')}`}:{ok:results.every(x=>x.ok===true)?true:null,results};}}catch(error){checks.routes={ok:false,error:error.message};}
  try{const models=await hfModels();checks.huggingface={ok:models.length>0,free_models_available:models.length};}catch(error){checks.huggingface={ok:false,error:error.message};}
  let purge={oauth_codes:0,oauth_tokens:0,oauth_clients:0};
  try{purge=await purgeOAuthData();checks.oauth_cleanup={ok:true,...purge};}catch(error){checks.oauth_cleanup={ok:false,error:error.message};}
  const anomalies=Object.entries(checks).filter(([key,v])=>v.ok===false&&!(key==='huggingface'&&!v.error)).map(([key,v])=>`${key}: ${v.error||'check failed'}`);
  const state=key=>(checks[key].ok===true?'ok':checks[key].ok===null?'inconclusive':'FAILED');
  const summary=anomalies.length?`Autonomous health check found issues: ${anomalies.join('; ')}`:`Autonomous health check: Vercel ${state('vercel')}, MCP endpoint ${state('mcp_endpoint')}, routes ${state('routes')}, ${checks.huggingface.free_models_available||0} free HF model(s) available, OAuth cleanup removed ${purge.oauth_codes} code(s), ${purge.oauth_tokens} token(s), ${purge.oauth_clients} client(s).`;
  const entry=await mutate(userId,current=>{const p=project(current,project_id);const record={id:crypto.randomUUID(),at:new Date().toISOString(),agent,checks,anomalies};p.health_checks=p.health_checks||[];p.health_checks.unshift(record);p.health_checks=p.health_checks.slice(0,50);p.blockers=(p.blockers||[]).filter(b=>!b.startsWith('[auto]'));if(anomalies.length)p.blockers.push(`[auto] ${summary}`);p.events.unshift({type:'health_check',agent,summary,at:record.at});p.events=p.events.slice(0,100);return record;});return{summary,checks,anomalies,at:entry.at};}
